### ISSUE TITLE
Hover Module Ascension bug

### ISSUE THREAD

**Issue by Alighierian** [budak7273/ArmorModules#3] opened 2020-10-08 11:31 UTC
**Describe the bug**
The new Hover Module has an issue related to ascending. When holding the space bar to ascend in hover mode, it occasionally has reduced vertical speed, up to half the expected speed. Sometimes it snaps out of it by itself, at other times I have to let go of the throttle and restart the movement for it to readjust. Rebooting the game did not appear to have any effect.

Edit: Another version I've experienced after some more playing is basically a complete loss of thrust. When I hold the space bar to ascend, it starts slowly descending after some sputtering, as if you're trying to fly whilst heavily overloaded. It only occurs whilst trying to ascend; whilst hovering and moving horizontally it's perfectly fine.

**To Reproduce**
Unknown. I think it might be related to repeatedly interacting with controls, as one normally would when moving about, but I haven't been able to consistently reproduce. The reduction seems to vary between 10% and 50% vertical speed. Sometimes it slowly builds from use to use, at other times it just goes straight to -50% vertical speed.

Edit: It's broken more than half of the time right now, with the power reduction varying, but I haven't been able to figure out what actually caused it in the first place. Initially, it worked as normal, but not long after some testing with the hover and 'vanilla' module, as well as both at the same time, it started having this issue.

**Expected behaviour**
Consistent maximum ascension speed.

**Multiplayer?**
Experienced as Single player, in a private session. Unknown if present in Multiplayer.

**Screenshots**
Video clip displaying the issue, with repeated full power -> full stop -> full power cycles experiencing varying ascension speeds.
https://youtu.be/Blq1y1P3GFI

**Additional context**
Mk2 suit
Equipped modules:
- Hover module
- Integrated Blade Runners
- Integrated Gas Mask
- Medium Health regen
- 2x Bioreactor

**Comment by budak7273** [comment] 2020-10-10 20:18
Thanks for the report!

I noticed this happening in some of my testing as well just last night. I'm pretty sure that it's caused by Nog's recent changes to the speed/FPS compensation code in [this version](https://ficsit.app/mod/7J2LyFzTakqPQ5/version/NES3L3gR7c8sW/view) of the base PowerSuit mod. The "new Hover Module" is actually just the previous version's jetpack module with a new icon - nothing actually changed on it functionality wise between versions of the mod.

I'm discussing this issue with Nog on discord, and I'll get back to you with the outcome of that.

In the mean time, try to make sure that Satisfactory is running as close to 60fps as possible. That should help the jetpack to be a bit more consistent.

**Comment by budak7273** [comment] 2020-10-10 20:22
A fix will be released soon; see [this issue](https://github.com/Nogg-aholic/PowerSuit/issues/2) for more details.

**Comment by Alighierian** [comment] 2020-10-10 20:23
Odds are it's indeed not the hover module. I tested the new 'Vanilla' pack again, and same issue there. I currently have most settings set to ultra, and it's hovering around the 35-40-ish FPS by now, according to MoarFactory's tablet anyway. I'll see if I can crank it up a bit as a temporary fix.

**Comment by budak7273** [comment] 2020-12-12 05:38
As of 2.0.0, this should definitely be fixed, so I'm going to close the issue. Please feel free to open it again if the problem persists.

**Closed as completed by budak7273** 2020-12-12 05:38 UTC
Labels: bug
