### ISSUE TITLE
Fuel/Integrated blade runners permanently stop working after suit runs out of power

### ISSUE THREAD

**Issue by MWire** [budak7273/ArmorModules#5] opened 2020-12-17 20:29 UTC
**Description**
The Fuel/Integrated blade runners stop working when MK1/MK2 suit reaches 0 charge without rebooting properly.

**To Reproduce**
1- Equip MK1/MK2 suit with fuel/integrated blade runners + jetpack + some fuel;
2- Fly around until the jetpack runs out of fuel and drains all power from the suit.
3 - Land before the suit reboots (orange power icon reaches 100%).
4 - The reboot sequence is interrupted as the jetpack stops drawing too much power
3- After this, sprint speed will be capped at base speed + 0.1 m/s , even when on 100% charge. Fuel runners continue to consume fuel without providing additional sprint speed. The suit/module needs to be removed and equipped again to fix this.

**Expected behavior**
1- The reboot sequence should probably not be interrupted 
2- The runners should work normally after charge is restored.

**Multiplayer?**
Not tested.

**Additonal notes**
This doesn't happen with the Biofuel suit. Tested with the MK1 and MK2 suit on two different saves.

**Comment by budak7273** [comment] 2020-12-19 01:12
I can confirm that this happens in my testing world as well.

I'm not sure why it isn't happening with the Biofuel suit - maybe because the overdraw timer is so short?

It seems to be connected to the suit completing a refuel while it is still restarting after an overdraw, which causes the restart to cancel early. I'm taking a look at it, but it could be a while until a fix.

**Comment by budak7273** [comment] 2020-12-19 06:48
This should be corrected in the next release of PowerSuit. It was a more straightforward fix than I expected.

**Comment by budak7273** [comment] 2020-12-21 01:54
Fixed in PowerSuit 0.4.1

**Closed as completed by budak7273** 2020-12-21 01:54 UTC
Labels: bug, base PowerSuit mod related
